--------------------------------------------------------
--  Arquivo criado - Quarta-feira-Setembro-12-2018   
--------------------------------------------------------
REM INSERTING into PROJETO_CONCLUSAO_DE_CURSO1.ALUNOENTITY
SET DEFINE OFF;
Insert into PROJETO_CONCLUSAO_DE_CURSO1.ALUNOENTITY (ID,TURMA_ID) values ('1','1');
REM INSERTING into PROJETO_CONCLUSAO_DE_CURSO1.CURSOENTITY
SET DEFINE OFF;
Insert into PROJETO_CONCLUSAO_DE_CURSO1.CURSOENTITY (ID,DESCRICAO,AREA,NOME) values ('1','ES','Tecnologia','Engenharia de Software');
Insert into PROJETO_CONCLUSAO_DE_CURSO1.CURSOENTITY (ID,DESCRICAO,AREA,NOME) values ('2','EC','Tecnologia','Engenharia de Computação');
Insert into PROJETO_CONCLUSAO_DE_CURSO1.CURSOENTITY (ID,DESCRICAO,AREA,NOME) values ('3','EM','Tecnologia','Engenharia de Mecânica');
Insert into PROJETO_CONCLUSAO_DE_CURSO1.CURSOENTITY (ID,DESCRICAO,AREA,NOME) values ('4','PS','Saúde','Psicologia');
REM INSERTING into PROJETO_CONCLUSAO_DE_CURSO1.PROFESSORENTITY
SET DEFINE OFF;
Insert into PROJETO_CONCLUSAO_DE_CURSO1.PROFESSORENTITY (ID,AREA,TURMA_ID) values ('1','Tecnologia','1');
REM INSERTING into PROJETO_CONCLUSAO_DE_CURSO1.SUBMISSAOENTITY
SET DEFINE OFF;
REM INSERTING into PROJETO_CONCLUSAO_DE_CURSO1.TURMAENTITY
SET DEFINE OFF;
Insert into PROJETO_CONCLUSAO_DE_CURSO1.TURMAENTITY (ID,ANOINICIAL,CURSO_ID) values ('1','2014','1');
Insert into PROJETO_CONCLUSAO_DE_CURSO1.TURMAENTITY (ID,ANOINICIAL,CURSO_ID) values ('2','2014','2');
Insert into PROJETO_CONCLUSAO_DE_CURSO1.TURMAENTITY (ID,ANOINICIAL,CURSO_ID) values ('3','2014','3');
Insert into PROJETO_CONCLUSAO_DE_CURSO1.TURMAENTITY (ID,ANOINICIAL,CURSO_ID) values ('4','2014','4');
REM INSERTING into PROJETO_CONCLUSAO_DE_CURSO1.USUARIOENTITY
SET DEFINE OFF;
Insert into PROJETO_CONCLUSAO_DE_CURSO1.USUARIOENTITY (ID,RA,EMAIL,SENHA,AREA,TURMA_ID) values ('1','111111','carloshsjbv@gmail.com','123','TI','1');
Insert into PROJETO_CONCLUSAO_DE_CURSO1.USUARIOENTITY (ID,RA,EMAIL,SENHA,AREA,TURMA_ID) values ('2','222222','carloshsjbv@gmail.com','123','TI','1');
Insert into PROJETO_CONCLUSAO_DE_CURSO1.USUARIOENTITY (ID,RA,EMAIL,SENHA,AREA,TURMA_ID) values ('3','333333','carloshsjbv@gmail.com','123','TI','1');
